import React, {useState} from 'react';
import { Button,  Modal } from 'react-bootstrap';
import { useTranslation } from 'react-i18next';
const FuncModal = () => {
      const { t } = useTranslation("common");
      const [showModal, setShowModal] = useState(false);
      const txt = `
        Um, I always felt like a square peg in a round hole and I felt like my patients were not doing anything nourishing in terms of food. Most of the issues I dealt with were wrapped around hip replacements and maybe some strokes here and there and some neurological diseases, but traditional medicine, you know, it looks to treat symptoms. You have a problem, we'll give you a drug and we didn't check for contraindications or maybe you're on another medicine. Honestly, functional medicine. That's the first place we're

going to ask. We're going to think, well, food is the first thing ties in our immune system. Welcome to the Inspired Living with Autoimmunity podcast. The podcast for high achievers who want to stay sharp, focused, and full of energy despite their diagnosis. with your host, National Board Certified Functional Medicine Health Coach, Julie Michaelelsson, where Julie helps you take your power back from autoimmunity. And now, here's your host, Julie [Music] Michaelelsson. Welcome back to the

Inspired Living with Autoimmunity podcast. I'm your host, Julie Michaelelsson. And today we're joined by Lori Graham, a leading expert in metabolic health and functional medicine who embodies the principles she teaches and is the author of dysfunctional medicine with over 40 years of experience in and multiple certifications including occupational therapy, a master's of science in exercise science, a postmasters certificate in clinical nutrition, and as a certified functional medicine

practitioner. She brings a unique science-based perspective to healthy aging. In today's conversation, we're talking about how the functional medicine approach to wellness can support vibrancy as we age. Lori shares her passion for empowering patients to lead their care and how it's never too late to feel better. Lori, welcome to the podcast. Thank you. This is going to be fun. This is going to be fun. and I um I've finally just made myself hit record so that everybody could get the

value from you. So I know you call yourself a recovering occupational therapist. Tell us a little bit about you know what shifted your your journey toward functional medicine. Um, I always felt like a square peg in a round hole and I I felt like my patients were not doing anything nourishing in terms of food. And most of the issues I dealt with were wrapped around hip replacements and maybe some strokes here and there and some neurological diseases. But the thing that became so palpable was a lot

of kids would bring their parents donuts and muffins from Shopright and just leave it on the counter. So you really got to see what people were eating. And I had this parallel life where I was honestly plantbased for many times. I went raw. I did lots of different things just to see. I was athletic. I really wanted to see what fueled me the best. And I always felt like if you just didn't eat like that, you might feel a little better. And you think work with a wonderful nature path who went to school

with Jeffrey Bland. Ah, how do you like that? I like that. And she said to me, you know, you should study functional medicine. I said, "Oh, okay. That sounds like an idea." And ironically, there was a program in New York City, so it made it really easily. That's great. Easy for me to do. and and my sense was that the doctors there were a breed different than the breed that well I didn't really partake in traditional medicine I had a naturopath I had a homeopath okay you know what I mean um so but but the

doctors there were dis disenfranchised from traditional medicine. Not so much that they were disenfranchised with pharma when it's needed, but they recognized that food was medicine and they just didn't know how to glue it together. And they were and and it was it was it was awe inspiring. It was it was Oh, here's a doctor I'll give my health to, you know. Right. Yeah. Right. Amazing. Well, thank your friend for all of us. Yeah, really it is it is amazing and and um there are so many

differences um which actually let's just start there. So you wrote a book called dysfunctional medicine. Yes. And my husband thought up the name and I said, "Oh my god, that's so good." And I don't want it to come across like I'm bashing medicine. And I'm not um I have a special needs child and honestly I mean his is a long story not for now but maybe another time you know over another coffee but but his was a blend of spiritual healing and also conventional medicine

and and I think medicine shines when there's emergency Emergency medicine shines. But medicine changed many years ago when the principles surrounding it like food be thy medicine changed and pharma got involved with the curriculum and I trace that in my book. But for me, I think that since so many patients worry about what it costs to see a functional medicine practitioner in the non-inurance model, that educating patients, yes, on on what they can do for their own health and also I would say how to leverage

what they know when they go to the doctor's office. Yeah. Which which is so empowering. It's very empowering. I jokingly say, you know, back in the day there was lots of talks uh talk about ambudsmen. We don't hear it that much in the mainstream, you know, now. But but that's what I'm doing. I'm I'm I'm They're the ombbudsmen for themselves because I'm teaching them. But traditional medicine, you know, you know this. It it looks to treat symptoms. You have a problem, we'll give you a drug

and oh, by the way, we didn't check for contraindications or maybe you're on another medicine. You know, ask your far people have to know to ask their pharmacist, right? And and traditional medicine shines though in emergency care. Absolutely. But with chronic disease where where food reigns, where Yeah. where you can take charge of your health through diet and lifestyle, honestly, why should medicine be paying for that? They should just pay for the blood test to follow you to see if you're outside the norm in some way. So,

traditional medicine is evidence-based. So is so is functional medicine. It's evidence-based. There are studies we rely on. Um, but we don't give meds just to treat symptoms. We look at what the root cause is. And traditional medicine doesn't look at root cause. I would also say that traditional medicine is very male centric in the sense that most of the studies speak about men. Sure. And the blood tests that are done are in much wider ranges. And I don't even know this for sure, but I'm going to half

guess except for female hormones that everything else is you you know typ typically actually and and let's talk about the differences in the testing because I know you're you are also of the test don't guess. Um, you know, there's certain things we all can be doing to be healthier and then there's the individualized, you know, the end of one. The end of one. Yeah. Yeah. Um, and so I know we're aligned in that individualized approach and optimization. When you're looking at

labs, you're looking for optimal for you. Um, I wrote an article a few years ago about that was in um, Best Holistic Life magazine about lab testing because the the reason the range is so wide is it's literally a bell curve on the average of everybody from that lab company that's taken the test. So that company from that lab company. So LabCor's vitamin D range is going to be different than Vibrance's vitamin D range. Especially you see the big difference in hormones because right if you're going, you know,

insurancebased testing, you're going to have a lot of older people not on hormones, right? If you go functional medicine testing, their ranges are going to be skewed a little more toward optimal because a lot of people are on hormone replacement. So it it is fascinating during co the some of the bigger you know can go anywhere and get a draw lab companies changed their vitamin D ranges because because during co people finally started taking vitamin D and so the one of them the range only I think went to like 40 or 60 you know

now it's 120. Yeah. Yeah. So, so you're really and if you look at how unwell we are, who wants to be in the middle of that range? Right. Right. Right. Right. So, Right. And and even the ranges sometimes could be skewed up. The optimal ranges can be screwed skewed not screwed skewed up or skewed down. They're not just in the middle somewhere. Right. Right. And so, you know, there are a couple of companies that have um they have algorithms that will actually take your blood test and put

them into optimal ranges and then connect the dots, which somebody who's doing more of like um orthomolelecular biochemistry, they really understand it. I'm not that person. I need I need support from like an algorithm. But it's amazing how different that range is. Yeah, it really is. And I think the the difference in um cuz I at my at my sickest was, you know, well, your blood looks your blood test looks fine. Always always looks fine. Um and that's so common. I hear it all the time. And part

of it is that that the te, you know, what they're testing for, again, back to they're not looking for root causes of anything. So, um, and it's not because they don't want to. That's just not the model. It's not what they're taught. Doctors don't get taught nutrition in medical school. So, there's there's a gap there. there's a tremendous gap, you know, and functional medicine also, they really do honor the individuals. So, when I do an assessment with somebody,

I'm taking 90 minutes. I'm a little slower than your husband might be. I'm But I'm also like I'm also coaching, you know what I mean? So, well, yeah. Asking different types of questions. And sometimes when I'm doing a history, I go, "Oh my god." Uhhuh. That's it. That's see it. Yeah. And traditional medicine doesn't necessarily take that time because they're boxed into these. First of all, the medical assistant is taking your blood pressure and, you know, taking

your pulse and they're asking the regular questions that they have to put into the EMR. But if it were the doctor doing it, honestly, they might actually be asking, "How are you, Mrs. Smith? Anything new?" Like, and and start things rolling. Yeah. you know, and getting and getting people open to talking more. Patients give you the answers. Oh, yeah. Even if they don't know it, they don't realize they don't recognize that that they're giving you the answers. Sure. Right. They don't. And I

I literally leave an hour and a half and I tell patients, "Leave me that hour and a half with you when I have to come up with a food plan." Yeah. Yeah. I want to make sure this is going to be successful for them, right? Yeah. Well, and even just to touch on the labs again, um any good practitioner isn't treating the lab results, right? You're treating the patient, right? So, I I hear that all the time. Um the to me the best example is hormones. Whether you're talking thyroid hormone or sex hormones, you

know, how do you feel? Right. Because I know for me where my free T3 needs to be to feel well. Right. Right. But I don't know what that number is for you. Right. Right. And you know, and that's interesting you say that because on my journey with my functional medicine practitioner, we were noticing my cholesterol going up. And I eat very plantforward. Yeah. I don't eat chicken. I don't eat meat. My choice. It's happened in college. It just the food was really bad in college. But but I'm I'm eating, you

know, fatty fish now. doing my So, so anyway, my cholesterol is going up. I'm not eating cholesterol to speak of. It's it's in some of the nuts and the seeds. But we now know that eating cholesterol doesn't raise cholesterol. We now know, right? But and then the other side of it is that it's going up because you're not making much estrogen anymore, lady. And my thyroid's struggling. So, you're right. So, this is a really great, you know, kind of example. I'm going to have a

visit soon after I get to go and get my blood test. But my I went on T porsine, NT thyroid, which is from porsine, which apparently doesn't have gluten, but armathyroid. Nathyroid's typically the cleaner the cleaner. But now we have people talking about not even taking that. But there's a lot. And and and listen, patients get confused by all this too. You and I both know that like they they don't know what it goes back to the individual. Like I so I take thyroid hormone and I have

interviewed people that that feel like you know I I don't want to well I will use the word like that's a failure. I feel the best I have felt in my life. I'm okay. I don't care. I don't get a prize. Right. Right. You you don't get a prize for this. No. So, and I don't eat pork, but I take So, there that's my personal But, but here's something interesting. My TSH went up. My cholesterol went higher. This is interesting. Everybody's different and that's the

thing. So, but you also did just mention because because I've had some stress recently. Okay. Um although that blood test was preceded the stress but we need cholesterol to make our hormones to make our hormones and even when we're at a point where we might not be making so many hormones our body is still going to try try it's still going to try. So so we need to look at things like inflammation we need to look at oxidative stress we need to look at how buoyant your LDL are. So, I have

this great scientist I work with who has this circle. You can find it on the web. It's just he happened to introduce it to me. And it shows how if you go on a statin, then you'll get diabetes. So, you'll take a diabetes med and then you'll get high blood pressure and then you'll take a high blood pressure med. And oh, then by the way, you'll get Alzheimer's. And I mean it's a little Debbie Downer and I don't know that it's 100% truth because there's some genetics

that play into this with you. Sure. And also depends on you're taking a statin and are you taking with your statin and what are you eating this whole time? How about this? You're a woman. I'm a woman. Yeah. We know our bones can get weaker because we're not making as much estrogen. So I say to my women aging and my a my a my women are aging with me like it's kind of funny that my population is an older population but um you know I'm 10 years older than when I started than when I

Right. Yeah. But I say you've got other levers to pull. You can do more resistance training. Right. Yeah. You can you can push you can you can push you can wear the weighted vest when you go for a walk or you walk your dog. Y there are more things that we can do to pull different levers. And then if that doesn't work then maybe you look at a medicine. But always we have to ask why. Right. Yeah. And I love the the pulling levers. I mean, it's the same as looking at genetics or taking into

account genetics, right? We can know predispositions, but let's change what's influencing our genetics, right? And and so I love that. And I and honestly, for me, it's really exciting that the longer you're doing this, the older your clients are getting. Here's why. it it because people are learning about functional medicine and there was this kind of false notion that it's too late for me, right? Like I'm I'm too old. Do you know you want to know what I did last Saturday? You're

going to love this. What' you do? I have two grandchildren. One is almost six, the other's almost four. And I jumped on a trampoline with both of them. Woohoo. Now, it's not like I haven't jumped on a trampoline, but I haven't jumped on a trampoline since my kids were little. Sure. But how many 68year-old women do you know who jump on a trampoline with their grandchildren? It's amazing. I can like list lympa lymphatic support, fun, joy, all the good neurotransmitters. Okay, great.

But that's but that's why we Yeah. You know, and and so the other thing about functional medicine, and your audience might know this, but food is medicine, right? The different colors and like I'm not as as extreme as what's his name? Brian Johnson. Yeah, I'm not extreme like that, but he really says it well. He says, "Everything I put in my mouth has a purpose." Now, I'm not that bad. But if I want or that good depending on if I want something really good, you know, my

really good is like taking a fig, not a fig, a date and popping some almond butter in it and two or three, you know, cacao chips. But listen, and here's the other thing about about my book mixed into this into this conversation. And you're the function medicine coach and you know, I didn't get here overnight. Sure. And you're not done. And I'm not done. But I used to take my kids snacks. Like I I was the shop the smart way. So I'd get a big bag of ruffle Ruffles and there were only three ingredients back

in the days. It was canola oil, which we all thought was good back then. Back then. And I put it in in Ziploc bags and then I'd eat the bag when they went to sleep. Well, I say that all the time. Like, you know, I wasn't born eating this way. For for me personally, it took me getting very sick to learn. I even, you know, we joke all the time because like my my oldest son has celiac and and he would be like, "You were trying to kill me. I'd be homesick and you'd be giving me saltines." And I'm like, well,

that's what my mom did, you know, like when when Well, guess what? If you have diarrhea, I mean, part of it is the salt to retain the fluids a little bit. Yeah. Yeah. Well, but it was the gluten is what was making him sick to begin with. But he didn't have any GI issues, so and but he has celiac, but that might have just like you said he had celiac, right? He does. Yeah. So, now you're giving me cause to think my mother had had we we called it colitis back in the day. I don't know if that's what she

really had, right? Because we've probably become more nuanced in sure in di diagnosis, but I when I did my genetics, there are two genes that govern celiac and I'm hetererozygous on one of those. That is a an Ashkanazi trait. It is an Ashkanazi trait. I knew it when I saw the curly hair. Yeah. But but that just, you know, like and and and then I work with I I I work with a lot of patients with GI issues and I don't know really how many women don't have some form of GI issues with our

hormones changing all the time. And honestly, like I think that's the first place as a functional medicine practitioner that in traditional medicine, nobody ever really asks you. But in functional medicine, that's the first place we're going to ask. We're going to think, well, food is the first thing that I call it the lowhanging fruit, right? We all low hanging fruit, but it's also it's a foreign body. It's either driving illness or driving wellness. Yeah. And your gut has to

discern, right? Right. Is is this nutrition or is there, you know, a bacteria I need to get rid of real quick. Yeah. Right. And I think, you know, also just on the topic of aging where this ties in, our immune system is supposed to decline as we get older, but I don't think it has to. I think I think we really just have to keep nourishing the healthy bugs in our garden. Yeah. And and some of the what we you know I I know I've heard you use my favorite word inflammaging. Um you know that we normalize so many of

these inflammationdriven declines and we just call it aging, right? Oh, I'm sore. I'm tired. I'm all all the things. My brain's not working as well. They all have reasons, you know, but also for those of us that have been on the earth for a while, well, the earth is a lot dirtier than it was 30 years ago. We deal with So, you know, of course, our immune system needs more support because it's it's bombarded. It's just dealing with a lot and honestly like I tell my patients

control what you can Yeah. You can't control everything. You're not going to live in a bubble, right? You know, you're not. But you can get and you don't have to to you can get a filter in your home and you can buy organic and you know or grow your food or grow your food or exercise and sweat it out and you can think about foods that open up your detoxification and your lymph. And as we're aging, as things are changing, you know, the rules do change because the hormones are changing. And you know,

one of the things I hear from women, I think this is the perfect place to talk about this is, you know, they want to become that perfect body again. And I think that's probably okay up to around 60. And I I've really shifted in this over the years, but honestly, like you don't want to be overweight, you want to build muscle. So get a body composition scale and follow your muscle instead of the total amount that you weigh. Follow your your muscle. That's funny cuz you said perfect body

and in my literally the words that popped into my brain were strong. Like the perfect body is strong, right? And and so yeah, we need to to shift our definition of what a perfect body is, right? And how about this? Since there still is a little bit of controversy around taking estrogen past 60, and I don't know if it's not in my world. Well, hang on. I'm going to say, but there are some people that you hear everything from you hear everything. So if you're if you're sorting through it and really trying to

find what your truth is, a little extra fat on your body, guess what? You make estrogen from the fat, right? And and so you don't want the visceral fat. You don't want to be tubby. Yeah. And you don't want too much eststerone which tends to be fat derived as well. I just think we have to we we have to be a little more muscle more muscle focused and you know you asked me before we got on about how was my day and you know I did my yoga class and I did yeah I do venyasa so it's pretty it's a strenuous

it's it's it's a heated room it's pretty strenuous and there are a lot of younger people that I aspire to be like But I'm really working on my balance these days. Like standing on so important. Yeah. Well, it's one of the most important longevity tools. People's lives get ruined. Yeah. In their 70s and 80s if they take a fall, right? It's not when you want to have surgery. No, for sure. And that's where that being strong and working on balance and you know you

don't have to be a supermodel like a a body that's functioning well and feels good is the ideal body right so you know I I laugh I I really grew up with an aversion to the word skinny because I was a very thin child. I was an eater. I was I did not have an eating disorder. My dad was skinny as a rail. He probably had celiac, too. Who knows? You know, likely. Um. Yeah. And so I have the that lens of, well, now I look back at that body that didn't have any extra body fat on it that most women would

like kill for. And I think, well, sure, I wasn't absorbing my nutrients. Right. Right. Right. Right. And they didn't know they didn't know about medical food for people like that to just get rises. They didn't they didn't have No. And I mean my dad tried I there I we went through a phase where he made me you know a milkshake every day with a with an egg in it, you know, like trying and I'm like, you know, Dad, I look just like you. Like it's not going to happen. It's

funny you should say that because I am I am weed avoidant. I am at this point in my life I am weed avoidant. Um but my parents used to have in in Long Island where I grew up they had Snider's pretzels and they got in a they got delivered in the can. In the can and I used to get constipated when I had one of those big pretzels. Uhhuh. Not constipated, constipated, but like it was just but it affected you the bathroom. Yeah. And you know that didn't make sense until I went to college when

Snider's pretzels weren't on the menu and and the meat was bad. And then I started eating like lots of salads. And I didn't grow up with lots of salads. It was iceberg. I did, but they were iceberg lettuce and maybe a tomato. That was and maybe a tomato. Right. But honestly, like they had lots of diversity of vegetables and different salads all over. And I worked for food service, so I read a Dell Davis, you know, diet for a small planet, and I was sold. So there I was eating lots of

vegetables, going to the bathroom regularly, novel, Snider pretzels. They were delicious. I I It's been decades and decades and my mouth is watering even though I I you could you could give me a whole can right now and I I have not willingly you know we in our household it's being glutened is a verb. it's something that happens to you because I will not, you know, people ask me all the do you ever cheat? And I'm like, if you had any idea how sick I get, you know, and that's the

beauty of when you find out for yourself, right? Like I It's your blueprint. It's your blue. There's things I'm sensitive to that I can have sometimes and they're nutrientdense and I'll have them on as a treat on occasion, right? You know, and like night shades, you know, right? But you can't you can't have a diet centered around it. And we know where we can push the envelope. And I say that to my patients if I put them through a weight loss plan. And I have a really good

effective weight loss plan that changes your awareness around food significantly. But I tell people, you're going to cheat a little bit and you're not going to let the scale go up 5 lbs. It'll go up 2 lb, right? And that's inflammation. That's That is right. And it'll come down as soon as you change course, but you're going to know where you can push the envelope a little bit. And that's you. And then I say, and guess what? And the rules are going to change every 10 years because you're a

woman. And we have to roll with those punches because what they do, they just they change. Yeah. Well, and I'm still experimenting with, you know, what I have learned in the past two years is I can eat tomatoes from my garden all summer long. No problem. No problem. Why? Because they're completely organic. I But if I buy organic tomatoes in the win now, I don't know. And I haven't played with seasonal eating. I try I I eat seasonalish. Um I don't know if it's a seasonal thing. I don't know if it's Is

your stomach better at during during season? Like during the growing season since you're eating more from the garden, would you say you see a change? My stomach's I mean when I'm eating like my stomach's fine, you know, unless I'm experimenting, right? But if youed from your garden, you would have less problem. It seems to be I mean because I thought like okay I'm finally like tomatoes are back in and no they're not but they're they are from the garden in the summer

right it's it's kind of wild you know so but that's question maybe organic isn't 100% organic because again we cannot trust 100% right we can't the labeling And there are certain like pesticides that are allowed I think when they say it's organic and it could be very they're very marginal but that might be what pushes you over the edge. It could be. But to your point of we're always changing you know there are things that I don't eat that every few years I'll be like how about now? You

know not gluten for me. That's not a right that's not an option. Not even worth the experiment, you know. Um, but it goes back to the beginning of the conversation about empowering people. When we teach people to to really pay attention to the signals that they're getting, right? They then we can shift course, right? We could do a reset. We can, you know, and people, you know, by and large, people think it's normal to have a foggy head in the morning. Think it's normal to be stiff in the morning. I'm not

stiff in the morning. No, I don't have It's all inflammation. years ago. Yeah, years ago I did, you know, but and you know, I have a wonderful husband who's has chronic lime and I'm the person who recognizes when it's happening again. And thankfully, I don't go after what he brings into the house for himself. But if he goes to processed food, yeah, all of a sudden he's coughing and then he gets a neck pain. Uhhuh. And then I go, "Oh, this sounds familiar. You need to go to your doctor and get a

lime test." Yeah. And we're in one of those cycles now. And you know, like it's it's his and and you know, for anybody who's listening to this, you may not have a partner that buys into what Sure. And you have to do what's right for you because Yeah. You cannot do what you cannot eat the way your partner eats just because it's easier, right? Yeah. And I love that you're dispel that's like excuse number one you hear all the time whether it's the partner or for

younger younger people it's oh my kids won't eat. I'm like your kids are going to eat what you put on the table. They are they're not going to skip very many meals at all. you know, and and so for me, the fun part about working with, you know, women raising families is changing that cycle of like, let's not, you know, your kids should be able to avoid the chronic illness and then need the big course correct in their 40s, 50s, 60s, 70s, you know, if if they just start right now eating real food.

Like, let's just start there. Real food. You are You are so right. You are so right. So, it's fun. But he's lucky he has and and then sometimes we're blessed and we have a partner who's dialed into us, you know. Well, my husband is very allowing. You know, years ago when we got married, I still had kids living in the house. And I said to him, I will cook the vegetables, but you will cook your meats because that's fair. You don't eat. Because I got to a point where I realized I wasn't eating enough protein

and I was living on protein shakes and I just said, I don't have the time to make your protein and make a different protein for me. Okay. Yeah. You know, and and and and I think we just we have to always honor what our body needs. Sure. and and and in you know just we we have to and we have to let our partners do what they because they might not be as motivated to do what you know you might be doing. If you have a health challenge you have to take if you're motivated to take care of it then take charge and

find a functional medicine person. Yeah. Absolutely. Only kind of person who's going to dig deeply enough. Yeah. Amen. Amazing. And so you do a lot of I know you do one-on-one as well, but you do a lot of group work. Yes. Basically, I have a few different tiers of service. When if I have somebody that really needs to make significant changes and they're coming from truly conventional, haven't taken a step in this direction yet. Sure. And if they can afford, I will put them in quite tight touch with me so that they're

texting me every day. I want to know what they're eating. We're changing things around. I meet with them every week, the first six weeks, and then every other week, and I try to wean them off, you know, about three to four months. That's kind of my signature program. Gotcha. Um, I do one-on-one visits. Mhm. Um with people that are highly motivated to follow through with the care plan and we do follow-up visits as needed and then I run groups. So right now I have like a weight loss group that I'm running and I'm starting

on April 10th my diabetes program. why I was inspired and I really mean inspired a woman and I can speak about this only because she's all over my Instagram page because otherwise I don't normally share patients stories um but she was looking to move onto her sailboat in Bise with where she is now and she was on insulin and two oral meds and her blood sugars were flirting in the 3 to 400 range. Yeah. And and honestly, the way it went was I put her on keto. Mhm. And she came down into the high

100s. The doctor took her off the oral meds and one day she's at about 120 and she said, "Should I take my insulin, you know, at dinner time?" And I said, "No, you need to call your doctor and find out if you need to take less, right? because you will be sleeping at night. Yeah. She never called him and she took her insulin and in the morning she got up and she was at about 60. Yeah. So she didn't have any glucose tubes or anything like that. So what she did was she took salt water taffy. She

didn't even have an corn starch. Have somebody bring me something. No. She said I found I found saltwater taffy. Fine. get your blood sugar up a little bit. She never looked back. Yeah. And I I see it over and over and over again. And and I love that that that wasn't the the start of the conversation, but it is important to highlight if you are on medication, whether it is because often they go hand inand blood pressure medication, anything for blood sugar, whether you know from metformin to

insulin to all of the GLP1s that are out there now, all the things because I I see it time and time again and that a if if it's if we're talking type two, that's a lifestyle illness and and all of that is reversible and you don't ever have to look back, but it is. So, I love that you you know, it's so important to be but you know, now now she's she changed her hemoglobin A1C went from 7.4 to 6.3. And so, she's insulin resistant. She's not really diabetic at this point in

time. She's insulin resistant. And she's now walking. Yeah. She's down in Bise. She is working out with a trainer doing weights. It's amazing. And we're going to use more herbal support now, you know, and and she's on a a CGM, so I see everything on the screen. Sure. Yeah. But but she like she loves having someone like me. Sure. To say, "You need to go out for a walk now. I just looked at you. Go for a walk. That's great. I love it. So, where can where can listeners find the book Dysfunctional

Medicine? The book is on Amazon, dysfunctional medicine. And where's the best place to find you? They should reach out to neutrifyyoulife.com. And that's all one word. N U T R I F Y O R. Like all one, not three separate words. All one.com. And I have a contact me button there. So if anybody really wants to talk to me, what I do, I do a complimentary 15 to 20 minute is this right for you kind of conversation and then we'll figure out what you need. So amazing Lori, I so I'm so excited that we connected. I love

that you are attracting a mature community. um because it just means that we're creating that the ripple is working right and we're we're creating the change. Um so thank you so much for sharing your time and your expertise with us and we are glad that you are recovering from that OT world and and joined us over here and you know you know that saying um be the change that you want to be. Yes. Amazing. Amazing. Oh, and I listeners are probably like, "Wait, wait, don't let her go yet." What

is one step that listeners can take starting today? It could be anything you want to throw at us to start to improve their health. Give up processed food. Yes. Yeah. Amazing. That that that one thing without any personalization will make a huge change across the board. Yes. Amen. Amen. Thank you so much. Thank you for everyone listening. Remember, you can get the transcripts and show notes by visiting inspiredliving.show. I hope you had a great time and enjoyed this episode as much as I did. Go find Lori. Thank you

for listening to Julie Michaelelsson's inspired living with autoimmunity. Did you enjoy this episode? Please like, share, and subscribe wherever you listen to podcasts. If you'd like to get a transcript of this and every other episode, just head on over to inspiredliving.show or click on the link in this episode's description. There you can also find everything we discussed in this episode, including links and information about our guest. You can even send in your questions to be answered by Julie in a future

episode. That's inspired.show. Until next time, this is Julie Michaelelsson's Inspired Living with Autoimmunity podcast, helping you take your power back.

      `
      const kristinatxt = `I'm Kristina and I'm a licensed dietitian my practice is here in Daren I also do a lot of tella Health work with folks all over the country so we're g to Let's stand up and stretch for a sec yeah we're going to do a little exercise stretch awesome yeah it feels good right Perfect all right when you're ready everybody sit down so I'd like to start by doing something called heart breathing so everybody I invite you to close your eyes you going put your hand over your heart which is

right in the center of your chest and we're going to take a nice big deep breath like big diaphragmatic breath and when you breathe out imagine that the air that you're breathing is coming out of your heart okay so we're going to take nice five or six deep breaths doing this all right everybody come on back back do you feel nice and centered and grounded in your body yeah heart heart Focus breathing helps you do that it's it's the initial base Tool uh from heart math I'm certified in heart math um actually

Tony Robbins is also certified in heart math and it was kind of a sign for me when I went to do his Unleash the Power Within and walk over the coals um I had been told you should really study this heart maath thing and bring it into your coaching practice and then when he talked about it I said okay it's a sign I'm going to learn how to do this and it changed my life because if you knew who I was before uh public speaking was something that gave me panic attacks like I would literally vomit before

having to speak to people and when I was a teacher back to school night was my least favorite night like hated it you know the parents coming in so um heart math has allowed me to I mean it's incredible that I could get up on stage and do this because I used to get crazy nervous even just say my name hi I'm Christina my favorite color is blue you know all that stuff so if you are struggling to regulate your emotions like we've talked about how stress impacts our food choices impacts the

choices that we make impacts our performance at work performance with our family um heart math gives you real tools that you can Implement in your life of taught it to CEOs golfers a lot of anxious teenagers out there it's amazing okay so I'm going to ask a little question a little interactivity with you guys what do Olympians leaders Navy Seals basically all successful people have in common besides the desire to be excellent what do you think shout some things out for me they eat well okay

maybe consistency great work ethic you know the answer okay discipline yes all you're all correct consistency so a bunch of things right but I'm going to talk to you today about resilience um because this is definitely something they all share oh I would love to teach everybody heart math okay so resilience is the capacity to prepare care for recover from adapt in the face of stress challenge or adversity so imagine it's like a battery we all get depleted sometimes and then other things charge up our

battery because we are energy systems that expand and renew this energy so no one teaches us this stuff in school like how to renew that battery how to sustain that energy and there are four domains of resilience I'm I'm going to focus today on physical and emotional um but at the center of this is something called coherence so when you do heart breathing it puts your body into a state of coherence um this wonderful story that I actually heard from Tony Robbins uh he worked with Andre Agy remember the

tennis player like okay we don't have anyone who's Too Young in this audience all right he was number one tennis player in the world and then he competed with Pete SAS for that number one spot and Andre Fell From Grace like I think he was you know taking some drugs and he didn't want to give up tennis but he fell out of placement he was beyond 150 in the world and he needed to get back on track so Tony came to his house it's not in his biography by the way he didn't include it it's interesting and

he played a a Ser a video basically of a highlight reel of all his winningest moments and stopped at one in particular one where he was kind of like doing this intimidating walk and staring down the other guy yeah the strut and so he paused it and he said Andre like what were you thinking and feeling in this moment what was going on and he's like oh yeah I woke up that morning and just I felt in every cell of my body that I was going to win and I just had utter confidence and I just was trying to

communicate that with my body language that that other guy shouldn't have even bothered to show up and he said well that's that's a peak State that's a performance State that's you you put you all your physical training and you put your emotional regulation together now all those hours of hitting that tennis ball like your body's not going to betray you you will win and so when we we start to practice emotional regulation and it's a it's a constant practice for me believe me but

having Tools in your toolkit like that's what it's about right cuz we all get knocked down we all do and then you got to get back up knock down get back up yeah so we're talking here today about metabolic Health um and we are living longer we are thanks to modern medicine but that's not really the name of the game it's like quality of life as you live longer and 80% of the population is going to get one of these diseases uh just because you're getting older and I don't subscribe to that I

just I say no so yeah yeah let's just say no to that and this is what we want it to look like you know this this graph shows that yes we're living you know like an average 78 years um but if you do your part right like okay you know you you get lab tests and you go do things and you exercise and you make good food choices and you you're around people you love and you're doing work you love and you know you make life count then the potential is is enormous because we're all going to go

we're all going to go but it ideally would look like this I'm here I'm here I'm here I'm here ciao okay so these are some things that we absolutely know for sure for sure for sure we know that social support is the number one like loneliness is a killer we saw that during the pandemic it's really terrible for your mental health um so social support is number one and if you're struggling with food getting with a support team you know in a community I have one Ben has one Robert has one you know um Dr TR

has a huge community so getting with a community is really really important um we also know and this is this is confounding to me but we know that caloric restriction does extend lifespan however we also know and it's in the zeist right now skeletal muscle is your single biggest longevity organ however you need to eat more to build muscle which is something that Robert is going to talk to us about um super important the skeletal muscle piece so you know this this maybe it's about the cycles that we go through with that we

also know that diet it just impacts multi-generations right so when you know Dr s is talking about heavy metals and all this you know all this pollution and now we're talking about microplastics it's going to four generations down the line the sedentary risk ratio um is a 3.0 so let me break that down what that is so not exercising and what Amy said is correct like don't exercise for weight loss you exercise for your metabolic Health um the risk ratio of smoking is 1.5 and what that means is that you're

one and a half times more likely to die from a complic ation related to smoking so the risk ratio of just being sedentary and not exercising is double that why any ideas more Frailty we're already losing muscle mass as we age so you need to preserve it you need to get better with each year um and why is muscle mass important insulin sensitivity yes that's your biggest site of glucose disposal it's like your metabolic snc we call it but also you want to be mobile and not fall down because the moment we fall

down the you know we we just break a hip you could you could be gone within the air so these are like five pillars to really be thinking about with your health these are all sort of like levers that you can pull on and personally you know we could do a whole talk on sleep physiology I think that's actually the basis of all of it because I know for myself and like sleep has been my personal Kryptonite um since I was a child uh that that really leads to good decision- making and like whether you have the

energy to have a good workout session you know um whether you make good choices with your food so like the sleep and like I mentioned earlier if you don't sleep for 5 days straight you're pre-diabetic boom so sleep super critical so how do we get best results my My Philosophy is that 80% of the whole game is your mindset so um we're talking about your behavior and habits we're talking about how you think about things and this emotional regulation piece it's it's bigger than

the the what you're eating honestly but I also believe having a good strategy is important so this is you know we love low carb it's a better strategy um but your strategy is I I believe very dictative on your personal genetics based on the lab tests you do maybe wear a continuous glucose monitor it gives you like any device is going to give you information and we have a lot of those tracking devices now which is great so here's my client Alex he did a test called the true age complete and in five short months he

reversed his aging his speed of Aging so um the trage complete gives you lots of different reports even like telr stem cells a whole bunch whole bunch of things so the genum pace is like an epigenetic clock there are lots of clocks that measure the speed of your aging but this happens to be a really good one and you can see that he gained like months so instead of Aging at 1 point2 times per biological year year in five short months which is nothing in in the in terms of Lifetime that now he's

aging like at 0.9 per biological year so this is just another report inside of the true age complete and then in five short months his fit age improved by four years imagine if I had this data it's so great um he's he was the first one to give it to me so I practice something called personalized nutrition and and it's it's what Dr John solo does too but um you really kind of want to look at the individuals person um my my specialty is is the neutrogenia data but I also do food sensitivities

and other lab tests and really take into account like an individual's life lifestyle um so personalized nutrition it's it's has actually a lot of data you can Google you can Google this there a lot of studies on it and what's cool is I found this study the food for me study which was the very first randomized control trial on personalized nutrition and was a cohort of seven countries that um that work together on this they looked at very specific uh genotypes fto is related to Gin like that hunger

hormone fads one is is omega-3 fatty acids tcf7l2 is related to carbohydrate usage apoe highly studied it's a cholesterol Gene um very related to Alzheimer's and MTHFR which is like one that a lot of people out in the space are empty HFR which is such an easy fix since 33% of the population has an issue converting um to folate take a supplement um but it was neat that that they had this data and what they found was that after six months people who actually receive personal advice like did much better in those labs like their

lab markers showed much improvement so here's an example of one of the tests I run this is an omega-3 index index and we know that like fatty acid profiles really important for managing inflammation in the body this one is very inexpensive it's $60 you can do a pin prick test at home and it's very valuable information so we know that omega-3 fatty acids do all this wonderful stuff okay this is the food sensitivity test I do it's called the p88 dietary antigen I used to run another one that didn't give

me very good data to be honest with you um this one does four different immune Pathways IG IG ig4 and complement and what's the the snippet I put here on this slide is that it shows all the antinutrients in food that one could possibly come across and you can see by reactivity uh what the the anti-nutrients that bring up the most problem and when you get to correlate this with genetic data so for example you see histamine there a lot of foods that are high histamine but might be considered healthy like fermented foods

so I have a histamine issue I don't tolerate histamine super well and histamine is very high in alcohol so don't don't tolerate that well uh smoked Foods aged cheeses um and fermented foods so I can have some but not a lot avocados even I can have some but not a lot okay uh this is the organic acids test this is this is a urine test so remember when I talked about metabolites in my intro the the byproducts of your metabol ISM so this shows all those byproducts like what does it look

like and this and this client of mine very high ketones coming out in his in his urine okay molds and MotoX sins so this is a test that I don't run very often I do it for very tough cases really mysterious cases people that are like I've seen all the doctors but I don't know what's going on with me and unfortunately you know molds are just a problem that are not quite recognized yet but they are this leading deil cause of debilitating fatigue I had um a client who did really well on her keto

diet she lost 25 lbs she was already on thyroid medicine we got that all dialed in she she was like I still just don't have any energy like it's and it's not the it's not the food she was way she was way fat adopted all that and I said let's let's she she has two kids who are like National rowers and when we looked at her genetics you have the Olympian genes you should be working out like you do you have these amazing Fitness genetics she's like I don't have energy

so we did this test and sure enough mold like really high mold and so and she lives uh in New York State close to some wetlands and so she had a mold person come in and assess her home and sure enough moldy home and uh and it was really causing her a lot of fatigue um I had another person like itchy skin all over just itchy but of course she only came to see me she wanted to lose 10 PBS that's like a lot of people they like SP lose a little weight and meanwhile like didn't think itchy skin all over was a huge

problem and and so cleaned up her diet okay great she was drinking a lot of wine um wine is very moldy um coffee can be very moldy certain nuts especially peanuts peanuts are very high in aoxin that first one and so then like the Itchy so cleaning up some things now she was just itchy on her wrists okay this itchy wrist thing is really weird let's do this mold test sure enough molds so now she needs to do like detoxification protocols and that's that's a that's a whole other thing now we know we can all go to Dr

Salo to get IV Therapy if we need to detox mold okay so this is another one this is a stool test and it it tests these six different areas um a lot of people with digestive issues right your your microbiome really talks to your brain so you want to make sure that all things are well with the microbiome and this is just a snippet of the test this shows gut barrier integrity and you see on the bottom it says hulin hulin happens when you eat wheat eat gluten that has been sprayed with glyphosate and are in this country is

sprayed with a lot of glyphosate so that causes leaky gut syndrome and leaky gut leads to autoimmune issues mood disorder joint pain you name it okay so um I you know I I I said I do this Neutrogena testing well what is neutrogenia it's the science of looking at the genetics of neutr nutition okay um we're not analyzing diseases and real problem genes but um you know we're all the same here in this room pretty much 99.9% but there is that tiny difference that 0.1 and it's the same with wolves

and dogs and we know how many breeds of dogs there are so that that's really like as nuanced as that so we are the same in a lot of ways and there's good solid information for all of us and then there's some things that we need to dial in more specifically to you and DNA is like a language so imagine you know the words coat goat and boat completely different words spelling change of one letter it's meaningful it's meaningful so your DNA is is this is this language the report I do it looks at mental

health genes which is really like interesting problem now um and we look at Pathways so you you can look at one Gene and know kind of what it does but you want to look at it in a context so you know we're looking at it systems cellular uh we're looking at cardiovasc vascular Health hormones energy you know different different areas I wanted to mention this this one because it pertains to my client Alex so mtnr1b it's a melatonin receptor Gene it what happens is with certain people who eat late at

night it really spikes glucose like glucose in such a way that it will lead to diabetes um even if you're eating low carb okay so uh and I've seen it now with several of my people on a CGM I kept telling Alex you need to eat earlier he's from he's from another country originally so culturally this was very hard for him and he would not change this until he started wearing a CGM and he started seeing red like all night long it scared him and that's where like a CGM is really really

helpful um he's not the only one who you know I kind of harp on this you know just be stop eating earlier stop eating earlier um and but when I see this Gene like you have to right so all right so the the three the three Big C's also um clock content calories like so the meal timing is your clock like when am I eating the content what am I eating what are you choosing to eat and then this calories piece like how much am I eating I used to fall into the camp and I think a lot of low carb people do like you can eat

as much as you want it doesn't matter you know um it's it's all about insulin it's just all about insulin there's like no no calories it actually was it was Robert Sykes who really uh made made a very convincing argument for me that like no the calories they really matter and I've seen it with my clients like I had a guy who was over 300 lb loveed to eat and we were doing low carb and he wasn't losing a pound like not a pound and so what are you doing and he was basically eating a Sherie board every

night before his dinner and I was like okay logically like you can't do that if you you know um but the whole idea of like tracking and getting precise and all this stuff like I I I had a mental block against it so um you know I I was a perfect intuitive eater like you know what Amy talks about like perfect but there is such a thing also there's the other side the uh for for those of you who like can cannot actually tend to undereat or be really good at your restriction um the C the calories and

he's going to talk about that it's important um so calories matter but I want to talk about a different kind of energy balance real quick before we break for lunch um constant energy expenditures without the balance of adequate rest and Recovery they're going to lead to your burnout errors health challenges diminished performance so heart math has done a lot of experiments to show what emotional disregulation will do to your physiology okay um this is a husband and wife arguing so you can

see argument happens here it's heated argument's over but he doesn't he doesn't cool down they've done they they did a really cool experiment with a police officer responding to a domestic abuse situation which is the scariest thing that a police officer can actually respond to and before learning heart math the police officer stayed disregulated for nearly 24 hours so imagine he's going home to Wife and Kids you know he show even shows up at work the next day not well not in his body so like

emotional disregulation um has a physiological impact on your heart and your muscle mass all the all the things like your body just doesn't work properly so I'm going to show you a quick quick movie you cover your ears you're not going to like this e [Music] you see the world through how you feel yes so what what is your emotional soundtrack so we have depleting and renewing emotions this these are all the consequences of emotions that deplete you reduced muscle mass brain cell death

impaired memory accelerated aging impaired mental function and diminished performance so stress is not just in your mind okay like your mind and body are not disconnected um renewing emotions you know expressing appreciation gratitude courage these increase your longevity increase your resilience improve your memory problem solving intuition and creativity improve your job performance and achievement and all of that it creates that state of coherence that's so important which is an optimal state in

which the heart mind and emotions are aligned and in sync so you too can be like Andre Agassi winning you know when when everything is firing you know it's not the skill like you can't do it it's just that everything is working together and then that and then your immune system and your hormones and your nervous system is it's like all functioning um together and this is because the heart and the brain are connected and the Heart sends more signals to the brain than the brain sends to the heart and

your heart when you you have an energy system this has been measured it it's like three feet past your body like people can feel your energy when you walk in the room like you know when you know someone's in a really bad mood and you're going to steer clear right or you walk into a space a shop a whatever and it's got a bad Vibe right so um like they've even done experiments you walk into a Subway or a crowded space and if you put you you start practicing heart coherence you can kind

of influence the space that you're in so that's pretty powerful um spouses they can they they regulate to each other's breathing uh there was a really cool experiment with a dog and a boy so the dog and the boy are separated in two different rooms and they're stressed out about it because they were together they got separated and then they they reunite the dog and the boy and their heart sinks up like they measure they have every know everybody hooked up and so when you're with people you love like

you tend to you know flow but it's a re it's a real thing so we're going to we're going to do quick coherence here before uh breaking for lunch so this is another added step to the heart breathing so you're going to focus your attention again area of your heart imagine your breath is flowing in and out of your heart or chest and you want to eventually get so good at this you don't need to put your hand on your heart you can just do quick coherence uh I did it once in the car in

the Bronx I was driving in the Bronx it was crazy traffic I'm like let me see I hooked myself up to my little monitor to see if I could do quick coherence with my eyes open and I succeeded I only stayed in like 10 seconds but I was I was proud of myself okay so we're going to inhale 5 Seconds exhale 5 seconds or whatever rhythm is good for you and while you're doing this guys make a sincere attempt to experience a regenerative feeling such as appreciation or care I like to think of my dogs kizman and Moxy but think of

something that you appreciate and love all right and come on back so with practice it it gets easier like if you find your mind wandering um but usually we get the warm fuzzies when we think about something that we love and then the next tool after that learning how to sustain it which is much much harder but at least if you practice this um out and about in the world like when things are not stressful because I had a client who this is so funny he he came in and that that initial heart breathing technique

was called neutral it's just put you in like in a neutral space not necessarily A positive spacing came Christina neutral is not working it's not working I say well you are you have you been practicing this you know every day like on the hour no I haven't you say you can't wait until the stressful moment hits and now that's that that's not going to do it right okay so Alex's pace of Aging in five months how did he do this what did he do I want to give you the I want to

give you some of the secrets besides the stopping eating earlier um he followed a low carb diet shocker he was doing 36-hour fasts one time a week the earlier dinner like I mentioned he started exercising oh um he was taking targeted supplements his sleep was pretty bad so um he took a vacation this busy CEO he needed a vacation and and we started doing some heart math so thank you everybody we're going to break now for lunch enjoy

`
    return (
        <>
         <Button className="custom-btn" onClick={() => setShowModal(true)}>
                        {t("Transcript")}
                      </Button>
                      <Modal show={showModal} onHide={() => setShowModal(false)} size="lg" centered className="custom-modal">
                    <Modal.Header closeButton>
                      <Modal.Title>{t("Transcript")}</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                      <p>{t(txt)}</p>
                      <p>{t(kristinatxt)}</p>
                    </Modal.Body>
                    <Modal.Footer>
                      <Button variant="secondary" onClick={() => setShowModal(false)}>
                        {t("Close")}
                      </Button>
                    </Modal.Footer>
        </Modal>
        </>
    )
}
export default FuncModal;