const Treatment = {
prevent: require("../images copy/prevent-wellness.webp"), 
detox: require("../images copy/detox.webp"),
acupuncture: require("../images copy/acupuncture.webp"), 
ayurveda: require("../images copy/ayurveda.webp"), 
stemcell: require("../images copy/Regenerative Ma.webp"), 
nutriton: require("../images copy/nutrition.webp"), 
chiro: require("../images copy/Chiropractic.webp"),
empower: require("../images copy/traans.webp"), 
ak: require("../images copy/dmedddd (4).webp"),
mindset:require("../images copy/mindd.webp"),
chelation: require("../images copy/chelation.webp"),
functionalmedicine: require("../images copy/func.webp"),
massage:require("../images copy/massage.webp"),
homeopath: require("../images copy/homeo.webp"),
breathwork:require("../images copy/breathworkk.webp"),
energy: require("../images copy/energy.webp"),
hypnotherapy:require("../images copy/hypno.webp"),
herbalmedicine:require("../images copy/HERBALMEDICINE .webp"),
meditation:require("../images copy/meditation.webp"),
naturopathy:require("../images copy/naturopathyy.webp"),
nutri:require("../images copy/nutrig.png"),
soundhealing:require("../images copy/sh.webp")
};
export default Treatment;
